apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: {{ .Values.appVersion }}
    spec:
      containers:
      - image: {{ .Values.imageName }}
        name: {{ .Values.appName }}-{{ randAlphaNum 5 | lower}}
        ports:
        - containerPort: {{ .Values.sourcePort }}